# Generated by Django 4.2.28 on 2026-02-21 14:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("link_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="applications/"),
                ),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "meta_thumbnail",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[1200, 630],
                        upload_to="thumbnails/",
                    ),
                ),
                (
                    "img_md",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=95,
                        scale=None,
                        size=[1280, 720],
                        upload_to="resized/",
                    ),
                ),
            ],
        ),
    ]
