# Generated by Django 4.2.7 on 2024-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website_link", models.TextField(blank=True, null=True)),
                ("link_name", models.CharField(blank=True, max_length=40, null=True)),
                ("blog_link", models.TextField(blank=True, null=True)),
                ("app_link", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website/App"),
                            ("graphic_design", "Graphic Design"),
                            ("ui_ux", "UI/UX"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
