# Generated by Django 5.0.2 on 2024-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
