# Generated by Django 5.0.2 on 2024-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image_placeholder_alter_project_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
