# Generated by Django 5.0.2 on 2024-11-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='projects/cover/'),
        ),
    ]
