# Generated by Django 5.0.2 on 2025-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_in_porfolio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='what_we_did',
            field=models.TextField(blank=True, null=True),
        ),
    ]
