# Generated by Django 5.2.1 on 2025-05-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_show_in_porfolio_project_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
    ]
