# Generated by Django 5.2.1 on 2025-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='similar_projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
