# Generated by Django 5.2.1 on 2025-05-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_client_project_content_and_more'),
        ('website', '0014_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testimonialk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.testimonial'),
        ),
    ]
