# Generated by Django 5.2.1 on 2025-05-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_testimonialk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='testimonial',
        ),
    ]
