# Generated by Django 5.2.1 on 2025-05-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='testimonialk',
            new_name='testimonial',
        ),
    ]
