# Generated by Django 5.0.2 on 2024-05-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_h1', models.CharField(blank=True, max_length=150, null=True)),
                ('hero_p', models.CharField(blank=True, max_length=150, null=True)),
                ('hero_btn_primary', models.CharField(blank=True, max_length=25, null=True)),
                ('hero_btn_secondary', models.CharField(blank=True, max_length=25, null=True)),
                ('card_1_icon', models.CharField(blank=True, max_length=70, null=True)),
                ('card_1_title', models.CharField(blank=True, max_length=25, null=True)),
                ('card_1_paragraph', models.TextField(blank=True, null=True)),
                ('card_2_icon', models.CharField(blank=True, max_length=70, null=True)),
                ('card_2_title', models.CharField(blank=True, max_length=25, null=True)),
                ('card_2_paragraph', models.TextField(blank=True, null=True)),
                ('card_3_icon', models.CharField(blank=True, max_length=70, null=True)),
                ('card_3_title', models.CharField(blank=True, max_length=25, null=True)),
                ('card_3_paragraph', models.TextField(blank=True, null=True)),
                ('about_us_h1', models.CharField(blank=True, max_length=50, null=True)),
                ('about_us_p', models.TextField(blank=True, null=True)),
                ('about_us_button', models.CharField(blank=True, max_length=20, null=True)),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('consent', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=70, null=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('post_testimonial', models.BooleanField(blank=True, default=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='testimonial.jpg', null=True, upload_to='testimonial-images/')),
            ],
        ),
    ]
