# Generated by Django 5.0.2 on 2024-09-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_testimonial_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
