# Generated by Django 5.0.2 on 2024-11-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
