# Generated by Django 5.0.2 on 2024-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contact_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
