# Generated by Django 5.0.2 on 2024-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_homepage_hero_image_alter_homepage_hero_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='struggling_image',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_us_image',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
