# Generated by Django 5.0.2 on 2024-11-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_homepage_struggling_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_h1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
