# Generated by Django 5.0.2 on 2024-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_homepage_about_us_h1'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='collabo_img_1',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_img_2',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_img_3',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_p_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_p_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_p_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_title_1',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_title_2',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collabo_title_3',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
