# Generated by Django 5.0.2 on 2024-11-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_homepage_collabo_img_1_homepage_collabo_img_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='process_image',
            field=models.FileField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
