# Generated by Django 5.0.2 on 2024-12-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_homepage_process_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
