# Generated by Django 4.2.7 on 2024-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("paragraph_1", models.TextField(blank=True, null=True)),
                ("paragraph_2", models.TextField(blank=True, null=True)),
                ("paragraph_3", models.TextField(blank=True, null=True)),
                ("conclusion", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=50, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="")),
                ("pub_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
