# Generated by Django 4.2.7 on 2024-05-29 08:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[1200, 600],
                upload_to="blogs/",
            ),
        ),
    ]
