# Generated by Django 4.2.7 on 2024-05-29 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
