# Generated by Django 4.2.7 on 2024-05-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_pub_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="NewBlog",
        ),
    ]
