# Generated by Django 4.2.7 on 2024-05-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_rename_blog_newblog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewBlog",
            new_name="Blog",
        ),
    ]
