# Generated by Django 4.2.7 on 2024-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_blog_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
